"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./dashboard.module.css";
type Usage={limitPerMinute:number;currentWindow:number;remaining:number;utilizationPercent:number;lastHour:number;today:number;cacheHitsToday:number};
type Crossing={id:string;name:string;status:string;stations?:any[]};
type Measurement={closeDeltaSeconds:number|null;openDeltaSeconds:number|null;measuredDurationSeconds:number|null;trains?:any[]};
type Ad={name:string;impressions:number;clicks:number;cpm:number};
const num=(v:any)=>Number.isFinite(Number(v))?Number(v):0;const avg=(a:number[])=>a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):null;
export default function Admin(){
 const[rows,setRows]=useState<Measurement[]>([]),[crossings,setCrossings]=useState<Crossing[]>([]),[ads,setAds]=useState<Ad[]>([]),[api,setApi]=useState<Usage|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);try{const [m,c,a,u]=await Promise.all([fetch("/api/measurements/stats",{cache:"no-store"}),fetch("/api/admin/crossings",{cache:"no-store"}),fetch("/api/admin/ads/stats",{cache:"no-store"}),fetch("/api/admin/api-usage",{cache:"no-store"})]);const [mj,cj,aj,uj]=await Promise.all([m.json(),c.json(),a.json(),u.json()]);if(!m.ok||!c.ok||!a.ok||!u.ok)throw new Error("Dashboard-Daten konnten nicht vollständig geladen werden.");setRows(Array.isArray(mj)?mj:[]);setCrossings(Array.isArray(cj)?cj:[]);setAds(Array.isArray(aj)?aj:[]);setApi(uj);setError("")}catch(e){setError(e instanceof Error?e.message:"Dashboard konnte nicht geladen werden.")}finally{setLoading(false)}}
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(t)},[]);
 const k=useMemo(()=>{const close=rows.map(r=>r.closeDeltaSeconds).filter((v):v is number=>v!==null),open=rows.map(r=>r.openDeltaSeconds).filter((v):v is number=>v!==null),dur=rows.map(r=>r.measuredDurationSeconds).filter((v):v is number=>v!==null);const imps=ads.reduce((s,r)=>s+num(r.impressions),0),clicks=ads.reduce((s,r)=>s+num(r.clicks),0);return{avgClose:avg(close),avgOpen:avg(open),avgDuration:avg(dur),imps,clicks,revenue:ads.reduce((s,r)=>s+num(r.impressions)/1000*num(r.cpm),0),ctr:imps?clicks/imps*100:0,active:crossings.filter(c=>c.status!=="inactive").length,stations:crossings.reduce((s,c)=>s+(c.stations?.length||0),0)}} ,[rows,crossings,ads]);
 const lines=useMemo(()=>{const m=new Map<string,number[]>();rows.forEach(r=>r.trains?.forEach(t=>{const l=String(t.line||t.category||"Unbekannt");if(!m.has(l))m.set(l,[]);if(r.closeDeltaSeconds!==null)m.get(l)!.push(r.closeDeltaSeconds)}));return Array.from(m.entries()).map(([line,v])=>({line,count:v.length,error:avg(v)})).sort((a,b)=>b.count-a.count).slice(0,6)},[rows]);
 const pct=Math.min(100,Math.max(0,api?.utilizationPercent||0));
 return <main className={styles.page}><div className={styles.wrap}><header className={styles.header}><div><div className={styles.eyebrow}>CROSSINGS · CONTROL CENTER</div><h1>Dashboard</h1><p>Systemzustand, Prognosequalität, API-Verbrauch und Monetarisierung.</p></div><button className={styles.refresh} onClick={()=>void load()}>{loading?"Aktualisiere…":"↻ Aktualisieren"}</button></header>{error&&<div className={styles.error}>{error}</div>}
 <Section title="System & Infrastruktur" text="Operativer Überblick über die aktuell verwalteten Bahnübergänge." link="/admin/crossings" linkText="BÜ verwalten →"><div className={styles.cards}><Card label="Aktive BÜs" value={k.active} sub={`${crossings.length} insgesamt`} tone="good"/><Card label="DB-Stationen" value={k.stations} sub="verknüpfte Beobachtungsstationen"/><Card label="Messungen" value={rows.length} sub={`${rows.filter(r=>r.closeDeltaSeconds!==null).length} mit Close-Istwert`}/><Card label="API · aktuelle Minute" value={api?`${api.currentWindow} / ${api.limitPerMinute}`:"–"} sub={api?`${api.remaining} Requests frei`:"nicht verfügbar"} tone={pct>=90?"bad":pct>=75?"warn":"good"}/></div></Section>
 <Section title="Prognose & Datenqualität" text="Kennzahlen aus den gemessenen tatsächlichen Schließungen."><div className={styles.panelGrid}><div className={styles.panel}><h3>Messgenauigkeit</h3><Metric label="Ø Schließfehler" value={k.avgClose===null?"–":`${k.avgClose} s`}/><Metric label="Ø Öffnungsfehler" value={k.avgOpen===null?"–":`${k.avgOpen} s`}/><Metric label="Ø Schließdauer" value={k.avgDuration===null?"–":`${k.avgDuration} s`}/><Metric label="Messungen mit Close-Istwert" value={rows.filter(r=>r.closeDeltaSeconds!==null).length}/></div><div className={styles.panel}><h3>Linien mit den meisten Messungen</h3><div className={styles.bars}>{lines.length?lines.map(r=><div className={styles.barRow} key={r.line}><span>{r.line}</span><div className={styles.barTrack}><div className={styles.barFill} style={{width:`${Math.max(8,r.count/(lines[0]?.count||1)*100)}%`}}/></div><strong>{r.error===null?"–":`${r.error}s`}</strong></div>):<span className={styles.sub}>Noch keine Linienmessungen vorhanden.</span>}</div></div></div></Section>
 <Section title="DB API" text="Das externe Rate-Limit ist das wichtigste operative Limit." link="/admin/crossings/api" linkText="API-Details →"><div className={styles.cards}><div className={`${styles.card} ${styles.api} ${pct>=90?styles.apiBad:pct>=75?styles.apiWarn:""}`}><span className={styles.label}>60-SEKUNDEN-FENSTER</span><div className={styles.value}>{api?api.currentWindow:"–"} <span style={{fontSize:15,color:"#aeb7c2"}}>/ {api?.limitPerMinute??"–"}</span></div><div className={styles.apiBar}><div className={styles.apiFill} style={{width:`${pct}%`}}/></div><span className={styles.sub}>{api?`${pct.toFixed(1)} % Auslastung · ${api.remaining} frei`:"–"}</span></div><Card label="Letzte Stunde" value={api?.lastHour.toLocaleString("de-DE")||"–"} sub="DB-Timetables Requests"/><Card label="Heute" value={api?.today.toLocaleString("de-DE")||"–"} sub="externe Requests"/><Card label="Cache-Hits" value={api?.cacheHitsToday.toLocaleString("de-DE")||"–"} sub="heute nicht extern abgefragt"/></div></Section>
 <Section title="Werbung & Monetarisierung" text="Aktuelle Performance der Werbeauslieferung." link="/admin/ads" linkText="Werbung verwalten →"><div className={styles.cards}><Card label="Impressions" value={k.imps.toLocaleString("de-DE")} sub="erfasste Ausspielungen"/><Card label="Clicks" value={k.clicks.toLocaleString("de-DE")} sub="erfasste Klicks"/><Card label="CTR" value={`${k.ctr.toFixed(2)} %`} sub="Clicks / Impressions" tone="good"/><Card label="Umsatz" value={`€ ${k.revenue.toFixed(2)}`} sub="aus aktuellem CPM-Modell" tone="good"/></div></Section>
 <Section title="Schnellzugriff" text="Direkt zu den operativen Bereichen."><div className={styles.quick}><a href="/admin/crossings"><strong>🚧 Bahnübergänge</strong><span>Standorte, Strecken, Stationen und Prognosen</span></a><a href="/admin/crossings/api"><strong>◉ DB API</strong><span>Rate-Limit, EVA-Verbrauch und Cache</span></a><a href="/admin/campaigns"><strong>◫ Kampagnen</strong><span>Werbekunden und Budgets</span></a><a href="/admin/measurements"><strong>✓ Messungen</strong><span>Feedback und Prognosequalität</span></a></div></Section></div></main>
}
function Section({title,text,link,linkText,children}:{title:string;text:string;link?:string;linkText?:string;children:React.ReactNode}){return <section className={styles.section}><div className={styles.sectionHead}><div><h2>{title}</h2><p>{text}</p></div>{link&&<a className={styles.link} href={link}>{linkText}</a>}</div>{children}</section>}
function Metric({label,value}:{label:string;value:string|number}){return <div className={styles.metricLine}><span>{label}</span><strong>{value}</strong></div>}
function Card({label,value,sub,tone}:{label:string;value:string|number;sub:string;tone?:"good"|"warn"|"bad"}){return <article className={styles.card}><div className={styles.label}>{label}</div><div className={`${styles.value} ${tone?styles[tone]:""}`}>{value}</div><div className={styles.sub}>{sub}</div></article>}
