"use client";
import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";
type StationLink={id?:string;eva:string;station_name:string;role:string;categories:string;direction:string;fallback_offset_seconds:number;track_distance_meters:number};
type ReferenceLineOption={line:string;stations:string[];stationCount:number};
type ReferenceStation={eva:string;name:string;role?:string};
type Props={crossingId:string;onClose:()=>void;onSaved?:()=>void};
const inputStyle:CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #dfe3e8",borderRadius:10,padding:"11px 12px",font:"inherit",fontSize:13};
const labelStyle:CSSProperties={fontSize:11,fontWeight:800,color:"#343c46"};
export default function EditCrossingDrawer({crossingId,onClose,onSaved}:Props){
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const[form,setForm]=useState({name:"",eva:"",lat:"",lon:"",closeOffsetSeconds:"80",openOffsetSeconds:"20",confidence:"0.5",status:"active"});
 const[routeStops,setRouteStops]=useState<string[]>([]),[links,setLinks]=useState<StationLink[]>([]);
 const[referenceLines,setReferenceLines]=useState<string[]>([]),[referenceLineOptions,setReferenceLineOptions]=useState<ReferenceLineOption[]>([]),[referenceStations,setReferenceStations]=useState<string[]>([]),[referenceStationOptions,setReferenceStationOptions]=useState<ReferenceStation[]>([]);
 const[referenceLineLoading,setReferenceLineLoading]=useState(false),[referenceStationLoading,setReferenceStationLoading]=useState(false);
 useEffect(()=>{let alive=true;(async()=>{try{const res=await fetch(`/api/admin/crossings/${encodeURIComponent(crossingId)}`,{cache:"no-store"});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Übergang konnte nicht geladen werden.");if(!alive)return;const c=data.crossing||{};setForm({name:String(c.name||""),eva:String(c.eva||""),lat:String(c.lat??""),lon:String(c.lon??""),closeOffsetSeconds:String(c.close_offset_seconds??80),openOffsetSeconds:String(c.open_offset_seconds??20),confidence:String(c.confidence??0.5),status:String(c.status||"active")});setRouteStops(Array.isArray(c.requiredRouteStops)?c.requiredRouteStops:[]);setReferenceLines(Array.isArray(c.referenceLines)?c.referenceLines:[]);setLinks(Array.isArray(data.stationLinks)?data.stationLinks:[]);const rs=await fetch(`/api/admin/crossings/${encodeURIComponent(crossingId)}/reference-stations`,{cache:"no-store"});const rd=await rs.json().catch(()=>({}));if(alive&&rs.ok)setReferenceStations(Array.isArray(rd.referenceStations)?rd.referenceStations:[]);}catch(e){if(alive)setError(e instanceof Error?e.message:"Laden fehlgeschlagen.");}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[crossingId]);
 useEffect(()=>{const evas=links.filter(l=>l.role==="primary"||l.role==="observation").map(l=>l.eva).filter(Boolean);if(!evas.length)return;let alive=true;setReferenceLineLoading(true);const p=new URLSearchParams();Array.from(new Set(evas)).slice(0,8).forEach(e=>p.append("eva",e));fetch(`/api/admin/crossings/reference-line-options?${p.toString()}`,{cache:"no-store"}).then(r=>r.json().catch(()=>({}))).then(d=>{if(alive)setReferenceLineOptions(Array.isArray(d.options)?d.options:[])}).catch(()=>{if(alive)setReferenceLineOptions([])}).finally(()=>{if(alive)setReferenceLineLoading(false)});return()=>{alive=false}},[links]);
 useEffect(()=>{const line=String(referenceLines[0]||"").trim();if(!line){setReferenceStationOptions([]);return}const evas=links.filter(l=>l.role==="primary"||l.role==="observation").map(l=>l.eva).filter(Boolean);let alive=true;setReferenceStationLoading(true);const p=new URLSearchParams({line});Array.from(new Set(evas)).slice(0,8).forEach(e=>p.append("eva",e));fetch(`/api/admin/crossings/reference-line-options?${p.toString()}`,{cache:"no-store"}).then(r=>r.json().catch(()=>({}))).then(d=>{if(alive)setReferenceStationOptions(Array.isArray(d.referenceStations)?d.referenceStations:[])}).catch(()=>{if(alive)setReferenceStationOptions([])}).finally(()=>{if(alive)setReferenceStationLoading(false)});return()=>{alive=false}},[referenceLines,links]);
 const mapSrc=useMemo(()=>{const lat=Number(form.lat),lon=Number(form.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return"";const d=.006;return`https://www.openstreetmap.org/export/embed.html?bbox=${lon-d},${lat-d},${lon+d},${lat+d}&layer=mapnik&marker=${lat},${lon}`},[form.lat,form.lon]);
 async function save(){setSaving(true);setError("");try{const res=await fetch(`/api/admin/crossings/${encodeURIComponent(crossingId)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.name,eva:form.eva,lat:Number(form.lat),lon:Number(form.lon),closeOffsetSeconds:Number(form.closeOffsetSeconds),openOffsetSeconds:Number(form.openOffsetSeconds),confidence:Number(form.confidence),status:form.status,requiredRouteStops:routeStops,referenceLines,stationLinks:links})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Speichern fehlgeschlagen.");const sr=await fetch(`/api/admin/crossings/${encodeURIComponent(crossingId)}/reference-stations`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({referenceStations})});const sd=await sr.json().catch(()=>({}));if(!sr.ok)throw new Error(sd.error||"Referenzbahnhöfe konnten nicht gespeichert werden.");onSaved?.();onClose()}catch(e){setError(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving(false)}}
 function setField(key:keyof typeof form,value:string){setForm(c=>({...c,[key]:value}))}function addStop(){setRouteStops(x=>[...x,""])}function addStation(){setLinks(x=>[...x,{eva:"",station_name:"",role:"observation",categories:"ICE,IC,EC,RE,RB",direction:"unknown",fallback_offset_seconds:0,track_distance_meters:0}])}
 return <div style={{position:"fixed",inset:0,zIndex:420,background:"rgba(15,20,28,.42)",display:"flex",justifyContent:"flex-end"}} onMouseDown={e=>e.target===e.currentTarget&&!saving&&onClose()}><aside style={{width:"min(760px,100vw)",height:"100%",background:"#fff",boxShadow:"-25px 0 70px rgba(0,0,0,.2)",display:"flex",flexDirection:"column"}} onMouseDown={e=>e.stopPropagation()}><header style={{padding:"26px 30px 20px",borderBottom:"1px solid #eceef1",display:"flex",justifyContent:"space-between",gap:20}}><div><div style={{color:"#e10600",fontSize:10,fontWeight:850,letterSpacing:".14em",marginBottom:7}}>BAHNÜBERGANG · BEARBEITEN</div><h2 style={{margin:0,fontSize:30,letterSpacing:"-.035em"}}>{form.name||"Übergang"}</h2></div><button onClick={onClose} disabled={saving} style={{border:0,background:"#f1f2f4",borderRadius:10,width:38,height:38,fontSize:24,cursor:"pointer"}}>×</button></header>{loading?<div style={{padding:30}}>Übergang wird geladen…</div>:<><div style={{overflow:"auto",padding:26,display:"grid",gap:24}}>{error&&<div style={{padding:12,borderRadius:10,background:"#fff4f4",border:"1px solid #f1d5d8",color:"#b4232d",fontSize:12}}>{error}</div>}
 <section style={{display:"grid",gap:10}}><strong style={{fontSize:13}}>Standort</strong><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{(["name","eva","lat","lon"] as const).map(k=><label key={k} style={{display:"grid",gap:6}}><span style={labelStyle}>{k==="name"?"Name":k==="eva"?"EVA":k==="lat"?"Latitude":"Longitude"}</span><input style={inputStyle} value={form[k]} onChange={e=>setField(k,e.target.value)}/></label>)}</div></section>
 {mapSrc&&<div style={{height:260,overflow:"hidden",borderRadius:14,border:"1px solid #dfe3e8"}}><iframe title="Standortkarte" src={mapSrc} style={{width:"100%",height:"100%",border:0}} loading="lazy"/></div>}
 <section style={{display:"grid",gap:10}}><strong style={{fontSize:13}}>Schließberechnung</strong><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10}}>{(["closeOffsetSeconds","openOffsetSeconds","confidence"] as const).map(k=><label key={k} style={{display:"grid",gap:6}}><span style={labelStyle}>{k==="closeOffsetSeconds"?"Schließ-Offset (Sek.)":k==="openOffsetSeconds"?"Öffnungs-Offset (Sek.)":"Konfidenz"}</span><input type="number" style={inputStyle} value={form[k]} onChange={e=>setField(k,e.target.value)}/></label>)}</div></section>
 <section style={{display:"grid",gap:10}}><div><strong style={{fontSize:13}}>Referenz für die Zugerkennung</strong><div style={{fontSize:11,color:"#6b7280",marginTop:3}}>Linie und anschließend die passenden Referenzbahnhöfe aus den hinterlegten DB-Stationen auswählen.</div></div><label style={{display:"grid",gap:6}}><span style={labelStyle}>Referenzlinie</span><select style={inputStyle} value={referenceLines[0]||""} onChange={e=>{setReferenceLines(e.target.value?[e.target.value]:[]);setReferenceStations([])}}><option value="">— Linie auswählen —</option>{referenceLineOptions.map(o=><option key={o.line} value={o.line}>{o.line} · {o.stations.join(", ")}</option>)}</select></label>{referenceLineLoading&&<span style={{fontSize:11,color:"#6b7280"}}>Linien werden aus dem Fahrplan ermittelt…</span>}{referenceLines[0]&&<label style={{display:"grid",gap:6}}><span style={labelStyle}>Referenzbahnhöfe</span><select multiple size={Math.min(6,Math.max(3,referenceStationOptions.length))} style={{...inputStyle,minHeight:100,padding:8}} value={referenceStations} onChange={e=>setReferenceStations(Array.from(e.target.selectedOptions).map(o=>o.value))}>{referenceStationOptions.length?referenceStationOptions.map(s=><option key={s.eva} value={s.eva}>{s.name} · EVA {s.eva}</option>):<option disabled>{referenceStationLoading?"Bahnhöfe werden ermittelt…":"Keine passenden Bahnhöfe gefunden."}</option>}</select></label>}{referenceStations.length>0&&<div style={{fontSize:12,color:"#343c46"}}><strong>Ausgewählt:</strong> {referenceStations.map(e=>referenceStationOptions.find(s=>s.eva===e)?.name||e).join(", ")}</div>}</section>
 <section style={{display:"grid",gap:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong style={{fontSize:13}}>Strecken-Haltepunkte</strong><button onClick={addStop} style={{border:0,background:"#f1f2f4",borderRadius:9,padding:"8px 11px",cursor:"pointer",fontWeight:750}}>+ Halt</button></div>{routeStops.map((stop,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr 34px",gap:8}}><input style={inputStyle} value={stop} onChange={e=>setRouteStops(x=>x.map((v,j)=>j===i?e.target.value:v))} placeholder="z. B. Bünde (Westf)"/><button onClick={()=>setRouteStops(x=>x.filter((_,j)=>j!==i))} style={{border:0,borderRadius:9,background:"#fff4f4",color:"#c1121f",fontSize:18,cursor:"pointer"}}>×</button></div>)}</section>
 <section style={{display:"grid",gap:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong style={{fontSize:13}}>DB-Beobachtungsstationen</strong><button onClick={addStation} style={{border:0,background:"#111827",color:"#fff",borderRadius:9,padding:"8px 11px",cursor:"pointer",fontWeight:750}}>+ Station</button></div>{links.map((link,i)=><div key={`${link.id||"new"}-${i}`} style={{padding:12,border:"1px solid #e5e7eb",borderRadius:11,display:"grid",gap:8}}><div style={{display:"grid",gridTemplateColumns:"110px 1fr 120px",gap:8}}><input style={inputStyle} placeholder="EVA" value={link.eva} onChange={e=>setLinks(x=>x.map((v,j)=>j===i?{...v,eva:e.target.value}:v))}/><input style={inputStyle} placeholder="Stationsname" value={link.station_name} onChange={e=>setLinks(x=>x.map((v,j)=>j===i?{...v,station_name:e.target.value}:v))}/><select style={inputStyle} value={link.role} onChange={e=>setLinks(x=>x.map((v,j)=>j===i?{...v,role:e.target.value}:v))}><option value="primary">primary</option><option value="observation">observation</option><option value="anchor">anchor</option></select></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 34px",gap:8}}><input style={inputStyle} placeholder="Kategorien, z. B. ICE,IC,RE" value={link.categories} onChange={e=>setLinks(x=>x.map((v,j)=>j===i?{...v,categories:e.target.value}:v))}/><select style={inputStyle} value={link.direction} onChange={e=>setLinks(x=>x.map((v,j)=>j===i?{...v,direction:e.target.value}:v))}><option value="unknown">Richtung unbekannt</option><option value="eastbound">eastbound</option><option value="westbound">westbound</option></select><button onClick={()=>setLinks(x=>x.filter((_,j)=>j!==i))} style={{border:0,borderRadius:9,background:"#fff4f4",color:"#c1121f",fontSize:18,cursor:"pointer"}}>×</button></div></div>)}</section>
 <section><label style={{display:"grid",gap:6}}><span style={labelStyle}>Status</span><select style={inputStyle} value={form.status} onChange={e=>setField("status",e.target.value)}><option value="active">active</option><option value="inactive">inactive</option></select></label></section></div><footer style={{padding:"16px 26px",borderTop:"1px solid #eceef1",display:"flex",justifyContent:"flex-end",gap:10}}><button onClick={onClose} disabled={saving} style={{border:0,borderRadius:10,padding:"12px 16px",background:"#f1f2f4",cursor:"pointer",fontWeight:750}}>Abbrechen</button><button onClick={()=>void save()} disabled={saving} style={{border:0,borderRadius:10,padding:"12px 18px",background:"#e10600",color:"#fff",cursor:"pointer",fontWeight:800}}>{saving?"Speichert…":"Änderungen speichern"}</button></footer></>}</aside></div>;
}
